#!/bin/bash
GIT_DOTFILES="$HOME/dotfiles"

copy_local_files_to_dotfiles(){
    cp "$HOME/.bashrc" $GIT_DOTFILES
    cp "$HOME/.config/nvim" $GIT_DOTFILES -r
}

copy_dotfiles_to_local_files(){
    cp "$GIT_DOTFILES/.bashrc" "$HOME/.bashrc"
    cp "$GIT_DOTFILES/.config/nvim" "$HOME/.config/nvim"
}

while getopts "capPh" opt; do
  case $opt in
    c) 
        copy_local_files_to_dotfiles
    ;;
    a) 
        copy_dotfiles_to_local_files
    ;;
    p) 
        git -C $GIT_DOTFILES pull
    ;;
    P) 
        git -C $GIT_DOTFILES add .
        git -C $GIT_DOTFILES commit -m "fix: dotfiles"
        git -C $GIT_DOTFILES push
    ;;
    h) help=1 
    ;;
  esac
done

if [[ $help -eq 1 ]]; then
  echo "Usage: $0 [-vh]"
  echo "-h: Display this help message"
  echo "-c: Copy the local files to the dotfiles"
  echo "-a: Apply the dotfiles to local files"
  echo "-p: Pull git repo"
  echo "-P: Push changes to git repo"
  exit 0
fi
