#!/bin/bash
DOTFILES_DIR="$HOME/dotfiles"

copy_local_files_to_dotfiles(){
    cp "$HOME/.bashrc" $DOTFILES_DIR
    cp "$HOME/.config/nvim" $DOTFILES_DIR -r
}

copy_dotfiles_to_local_files(){
    cp "$DOTFILES_DIR/.bashrc" "$HOME/.bashrc"
    cp "$DOTFILES_DIR/nvim" "$HOME/.config/nvim" -r
}

while getopts "capPh" opt; do
  case $opt in
    c) 
        copy_local_files_to_dotfiles
    ;;
    a) 
        copy_dotfiles_to_local_files
    ;;
    p) 
        git -C $DOTFILES_DIR pull
    ;;
    P) 
        git -C $DOTFILES_DIR add .
        git -C $DOTFILES_DIR commit -m "fix: dotfiles"
        git -C $DOTFILES_DIR push
    ;;
    h) help=1 
    ;;
  esac
done

if [[ $help -eq 1 ]]; then
  echo "Usage: $0 [-vh]"
  echo "-h: Display this help message"
  echo "-c: Copy the local files to the dotfiles"
  echo "-a: Apply the dotfiles to local files"
  echo "-p: Pull git repo"
  echo "-P: Push changes to git repo"
  exit 0
fi
